spring:
  application:
    name: availability-service
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL15Dialect
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/airbnb_availability_service
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  redis:
    host: localhost
    port: 6379
    timeout: 2000
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

server:
  port: 8003
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
  tracing:
    sampling:
      probability: 1.0

springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /swagger-ui.html
